tracer.property: "I AM THE DEFAULT ACCOUNT CONFIGURATION"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://152.136.155.204:3316/blogdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8"
spring.datasource.username: "blog"
#Spring Config配置服务器要求所有已加密的属性前加上{cipher}，通知服务器处理已加密的值
#通过http://localhost:8888/encrypt进行加密操作
spring.datasource.password: "{cipher}607e485ddb28860c99fd3f19807482f3463e5243010ab20ea006acc02dd1ed04"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"



