#-----------------Eureka配置-----------------------
eureka:
  instance:
    #将服务的IP地址而不是服务的主机名注册到Eureka
    prefer-ip-address: true
    # Eureka客户端需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (单位是秒)
    lease-renewal-interval-in-seconds: 30
    # Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒 (单位是秒)
    lease-expiration-duration-in-seconds: 90
  client:
    #触发器，是否通过Eureka注册本服务
    register-with-eureka: true
    #告知Spring Eureka客户端是否获取注册表的本地副本。将此属性设置为true将在本地缓存注册表
    fetch-registry: true
    #Eureka服务的列表，列表以逗号分隔（Eureka集群）
    #service-url的配置内容是map，map的内容是可以自己发挥的，只要是key: value格式就行（注意有个空格）
    service-url:
      defaultZone: http://localhost:8761/eureka

#-----------------Feign配置-----------------------
feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true

#-----------------Hystrix配置-----------------------
hystrix:
  # === === === == 默认Command === === === ==
  command:
    default:
      execution:
        isolation:
          # 调用隔离方式, 默认: 采用线程隔离, ExecutionIsolationStrategy:THREAD
          strategy: THREAD
          # 调用超时时间, 默认: 5 秒
          thread:
            timeoutInMilliseconds: 8000
          # 使用信号量隔离时, 命令调用最大的并发数
          semaphore:
            maxConcurrentRequests: 10
      #使用信号量隔离时, 命令fallback调用最大的并发数
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 10
      # === === === == 熔断器 === === === ==
      circuitBreaker:
        # 熔断器在整个统计时间内是否开启的阀值, 默认20个请求
        requestVolumeThreshold: 8
        # 熔断器默认工作时间, 默认: 5 秒
        sleepWindowInMilliseconds: 5
        # 默认: 50%, 当出错率超过50% 后熔断器启动
        errorThresholdPercentage: 50
        # 是否强制开启熔断器阻断所有请求, 默认: false, 不开启
        forceOpen: false
        # 是否允许熔断器忽略错误, 默认false, 不开启
        forceClosed: false
  # === === === == 线程池 === === === ==
  threadPool:
    default:
      # 配置线程池大小, 默认值10个
      coreSize: 0
      # 配置队列长度, 默认-1使用SynchronousQueue,其他值则使用LinkedBlockingQueue:不可动态修改:
      maxQueueSize: -1
      # 队列拒绝的阈值,可通过修改这个变量动态修改允许排队的长度: maxQueueSize=-1时不适用:
      queueSizeRejectionThreshold: 5
      # 线程生存时间, 默认1分钟
      keepAliveTimeMinutes: 1

#加载.yml文件定义的数据
testLoadData:
  testA: 111
  testB: 222
  testC: 333